language: go
go:
  - 1.x
install:
  - go get -u github.com/dave/courtney
  - go get -u github.com/kardianos/govendor
  - govendor sync
script:
  - courtney -t="-race" -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
